# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - Rscript -e "install.packages('http://biodev.cea.fr/sgcca/gliomaData_0.4.tar.gz')"
after_success:
  - Rscript -e 'covr::codecov()'
os:
  - linux
r:
 - bioc-release
notifications:
  email:
    on_success: change
    on_failure: change
